### PR TITLE
add calculator example

### PR DESCRIPTION
**Pull request by ericprud**
I tried for a demo that was detailed enough to exemplify use but simple enough to easily grok.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks! This is helpful as a learning tool. Appreciate it!

The test failures are probably a permissions issue, no big deal.

**Comment by nolanlawson** [comment]
Ah it's actually a style/lint issue. I'll fix it.

**Comment by ericprud** [comment]
I have an idea for another which would show an AsyncIterator running across a worker pipe. If you think it would be helpful, I can do another PR.

Tx for the lint fixes. I have a better idea how to look for and tackle them now.

**Comment by nolanlawson** [comment]
@ericprud I think having one simple example is probably best, although maybe this could be a code snippet in the README instead? If the goal is to show how to use AsyncIterators with the library.

**Pull request merged**
